//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace StateMachineDemo
{
    public class HoppingState:State
    {
        public HoppingState(Rabbit rabbit):base(rabbit)
        {
        }
        
        public override void Enter()
        {
            Console.WriteLine("I think I'll hop along for a little while");
        }
        
        public override void Exit()
        {
            Console.WriteLine("I'm done hopping for now");
        }
        
        public override void Update()
        {
            if (rabbit.tiredness > 50)
            {
                rabbit.stateMachine.ChangeState(new SleepingState(rabbit));
            }
            
            if (rabbit.hunger > 10)
            {
                rabbit.stateMachine.ChangeState(new EatingState(rabbit));
            }
            
            if (rabbit.bowels > 15)
            {
                rabbit.stateMachine.ChangeState(new PooingState(rabbit));
            }
        }
    }
}

