//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace StateMachineDemo
{
    public class PooingState:State
    {
        public PooingState(Rabbit rabbit):base(rabbit)
        {
        }
        
        public override void Enter()
        {
            Console.WriteLine("Going for a poo now");
            
        }
        
        public override void Exit()
        {
            Console.WriteLine("That was a nice poo");
        }
        
        public override void Update()
        {
            rabbit.bowels -=2;
            Console.WriteLine("Pooing");
            
            if (rabbit.bowels <= 0)
            {
                rabbit.bowels = 0;
                rabbit.stateMachine.ChangeState(new HoppingState(rabbit));
            }
            
            if (rabbit.hunger > 10)
            {
                rabbit.stateMachine.ChangeState(new EatingState(rabbit));
            }            
        }
    }
}

