//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace StateMachineDemo
{
    public class SleepingState:State
    {
        public SleepingState(Rabbit rabbit):base(rabbit)
        {
        }
        
        public override void Enter()
        {
            Console.WriteLine("Going to bed now. So sleepy!");
        }
        
        public override void Exit()
        {
            Console.WriteLine("Waking up to a nice cup of coffee!");            
        }
        
        public override void Update()
        {
            rabbit.tiredness -= 2;
            Console.WriteLine("Snore snore!");
            if (rabbit.tiredness < 0)
            {
                rabbit.tiredness = 0;
                rabbit.stateMachine.ChangeState(new HoppingState(rabbit));
            }
            
            if (rabbit.hunger > 20)
            {
                rabbit.stateMachine.ChangeState(new EatingState(rabbit));
            }
            
            if (rabbit.bowels > 20)
            {
                rabbit.stateMachine.ChangeState(new PooingState(rabbit));                
            }
        }
    }
}

